/**
 * Module for managing the PracticalplantsCrop type, and for converting
 * it to the powerplant Crop type. PracticalplantsCrop is symmetric to
 * the practicalplants.org MediaWiki format, it should be easy to transfer
 * data from a practicalplants wiki to powerplant.
 * 
 * @namespace practicalplants-crop
 * @memberof shared
 */

/**
 * @typedef {Object} PracticalplantsCrop
 *
 * TODO Document properties and possible quirks in their values.
 */

const Crop = require('./crop.js');

/**
 * @param {PracticalplantsCrop[]} practicalplantsCrop
 * @return {Crop[]}
 */
function convertToCrops(practicalplantsCrops) {
  return practicalplantsCrops.map(crop => convertToCrop(crop));
}

/**
 * @param {PracticalplantsCrop} practicalplantsCrop
 * @return {Crop}
 */
function convertToCrop(practicalplantsCrop) {
  const crop = {};

  const BOOLEAN_CONVERSIONS = [
    {practicalplantsValues: ['No', 'False'], cropValue: 'false'},
    {practicalplantsValues: ['Yes', 'True'], cropValue: 'true'}
  ];

  copyProperty(practicalplantsCrop, crop, 'binomial', 'binomialName', []);
  copyProperty(practicalplantsCrop, crop, 'common', 'commonName', [
  {practicalplantsValues: ['common bean, string bean, field bean, flageolet bean, French bean, garden bean, haricot bean, pop bean, snap bean'], 
    cropValue: 'Common bean, string bean, field bean, flageolet bean, French bean, garden bean, haricot bean, pop bean, snap bean'}]);
  copyProperty(practicalplantsCrop, crop, 'family', 'family', []);
  copyProperty(practicalplantsCrop, crop, 'genus', 'genus', []);
  copyProperty(practicalplantsCrop, crop, 'hardiness zone', 'hardinessZone', []);
  copyProperty(practicalplantsCrop, crop, 'mature height', 'matureHeight', []);
  copyProperty(practicalplantsCrop, crop, 'mature width', 'matureWidth', []);
  copyProperty(practicalplantsCrop, crop, 'poornutrition', 'poorNutrition', BOOLEAN_CONVERSIONS);
  copyProperty(practicalplantsCrop, crop, 'wind', 'wind', BOOLEAN_CONVERSIONS);
  copyProperty(practicalplantsCrop, crop, 'maritime', 'maritime', BOOLEAN_CONVERSIONS);
  copyProperty(practicalplantsCrop, crop, 'pollution', 'pollution', BOOLEAN_CONVERSIONS);
  copyProperty(practicalplantsCrop, crop, 'soil texture', 'soilTexture', []);
  copyProperty(practicalplantsCrop, crop, 'soil ph', 'soilPh', []);
  copyProperty(practicalplantsCrop, crop, 'soil water retention', 'soilWaterRetention', []);
  copyProperty(practicalplantsCrop, crop, 'ecosystem niche', 'ecosystemNiche', []);
  copyProperty(practicalplantsCrop, crop, 'life cycle', 'lifeCycle', []);
  copyProperty(practicalplantsCrop, crop, 'pollinators', 'pollinators', [{practicalplantsValues: ['Bees. self'], cropValue: ['bees', 'self']},
  {practicalplantsValues: ['Hover-flies', 'Hoverflies'], cropValue: ['hoverflies']},
  {practicalplantsValues: ['Apomyctic', 'Apomixy', 'Apomictic'], cropValue: ['apomictic']},
  {practicalplantsValues: ['Cleistogamous', 'Cleistogomous', 'Cleistogomy', 'Cleistogamy'], cropValue: ['cleistogamous']},
  {practicalplantsValues: ['Flies and small bees'], cropValue: ['flies', 'bees']},
  {practicalplantsValues: ['Bees. lepidoptera'], cropValue: ['bees', 'lepidoptera']},
  {practicalplantsValues: ['Lepidoptera', 'lepdioptera', 'Lepdioptera'], cropValue: ['lepidoptera']},
  {practicalplantsValues: ['Humble bees'], cropValue: ['bumblebees']},
  {practicalplantsValues: ['Flies lepidoptera'], cropValue: ['flies', 'lepidoptera']},
  {practicalplantsValues: ['Self. Occasionally flies'], cropValue: ['flies', 'self']},
  {practicalplantsValues: ['Self. Occasionally bees'], cropValue: ['bees', 'self']},
  {practicalplantsValues: ['Insects? Self'], cropValue: ['insects', 'self']},
  {practicalplantsValues: ['Self?'], cropValue: ['self']},
  {practicalplantsValues: ['Insect', 'Insects'], cropValue: ['insects']}]);
  copyProperty(practicalplantsCrop, crop, 'grow from', 'growFrom', []);
  copyProperty(practicalplantsCrop, crop, 'cutting type', 'cuttingType', []);
  copyProperty(practicalplantsCrop, crop, 'fertility', 'fertility', []);
  copyProperty(practicalplantsCrop, crop, 'functions', 'functions', [
  {practicalplantsValues: ['Biogenic Decalcifier/Pioneer Species'], cropValue: ['biogenic decalcifier', 'pioneer']},
  {practicalplantsValues: [''], cropValue: []}]);
  copyProperty(practicalplantsCrop, crop, 'shade', 'shade', []);
  copyProperty(practicalplantsCrop, crop, 'sun', 'sun', []);
  copyProperty(practicalplantsCrop, crop, 'water', 'water', []);
  copyProperty(practicalplantsCrop, crop, 'drought', 'drought', []);
  copyProperty(practicalplantsCrop, crop, 'herbaceous or woody', 'herbaceousOrWoody', []);
  copyProperty(practicalplantsCrop, crop, 'deciduous or evergreen', 'deciduousOrEvergreen', []);
  copyProperty(practicalplantsCrop, crop, 'growth rate', 'growthRate', []);
  copyProperty(practicalplantsCrop, crop, 'mature measurement unit', 'matureMeasurementUnit', [{practicalplantsValues: ['metres'], cropValue: 'meters'}]);
  copyProperty(practicalplantsCrop, crop, 'flower type', 'flowerType', []);
  copyProperty(practicalplantsCrop, crop, 'root zone', 'rootZone', []);
  copyProperty(practicalplantsCrop, crop, 'salinity', 'salinity', []);

  return crop;
}

/**
 * Copy property from a PracticalplantsCrop to a Crop, normalizing its value.
 * 
 * @param {PracticalplantsCrop} practicalplantsCrop
 * @param {Crop} crop
 * @param {String} practicalplantsProperty
 * @param {String} cropProperty
 * @param {Object} conversions
 */
function copyProperty(practicalplantsCrop, crop, practicalplantsProperty, cropProperty, conversions) {
  const practicalplantsValue = practicalplantsCrop[practicalplantsProperty];
  const arrayProperty = Crop.ARRAY_PROPERTIES.includes(cropProperty);

  /* First check if this property doesn't need conversion. */
  const emptyValues = [undefined, null, '', '\n'];
  if (emptyValues.includes(practicalplantsValue)) {
    crop[cropProperty] = arrayProperty ? [] : null;
    return;
  }

  if (Crop.NUMBER_PROPERTIES.includes(cropProperty)) {
    /* TODO Sometimes the properties matureWidth and matureHeight contain a range, for these store the value always as a range and provide functions to access the value? */
    crop[cropProperty] = parseFloat(practicalplantsCrop[practicalplantsProperty]);
    return;
  }

  /* Apply conversion. */
  let cropValue;
  if (arrayProperty) {
    let input;
    if (cropProperty === 'functions' && !Array.isArray(practicalplantsValue)) {
      input = practicalplantsValue['function'];
    } else {
      input = practicalplantsValue;
    }
    let practicalplantsArray = removeDuplicates(getAsArray(input));

    let cropArray = [];
    for (let i = 0; i < practicalplantsArray.length; i++) {
      const cropArrayValue = convertToCropValue(conversions, practicalplantsArray[i], cropProperty);
      if (Array.isArray(cropArrayValue)) {
        cropArray.push(...cropArrayValue);
      } else {
        cropArray.push(cropArrayValue);
      }
    }
    cropValue = cropArray;
  } else {
    cropValue = convertToCropValue(conversions, practicalplantsValue, cropProperty);
  }
  crop[cropProperty] = cropValue;
}

/**
 * @param {Object[]} conversions
 * @param {Object} practicalplantsValue
 * @param {String} cropProperty
 * @return {Object}
 */
function convertToCropValue(conversions, practicalplantsValue, cropProperty) {
  for (let i = 0; i < conversions.length; i++) {
    const conversion = conversions[i];
    if (conversion.practicalplantsValues.some(value => (value == practicalplantsValue))) {
      return conversion.cropValue;
    }
  }
  return Crop.NAME_PROPERTIES.includes(cropProperty) ? practicalplantsValue : practicalplantsValue.toLowerCase();
}

/**
 * @param {String} line
 * @return {Object[]}
 */
function getAsArray(value) {
  return typeof value === 'object' ? value : parseCsvLine(value);
}
 
/**
 * @param {String} line
 * @return {Object[]}
 */
function parseCsvLine(line) {
  return line.split(',').map(value => value.trim());
}

/**
 * @param {Object[]} array
 * @return {Object[]}
 */
function removeDuplicates(array) {
  return array.filter(value => (count(array, value) === 1));
}

/**
 * @param {Object[]} array
 * @param {Object} value
 * @return {Number}
 */
function count(array, value) {
  let counter = 0;
  array.forEach(element => {
    if (element == value) {
      counter++;
    }
  });
  return counter;
}

/*
 * All possible properties that may appear in raw practicalplants.org data.
 */
const PROPERTIES = [
  'append to article summary',
  'article summary',
  'primary image',
  'binomial',
  'genus',
  'family',
  'life cycle',
  'herbaceous or woody',
  'deciduous or evergreen',
  'flower type',
  'growth rate',
  'mature height',
  'mature width',
  'sun',
  'shade',
  'hardiness zone',
  'water',
  'drought',
  'soil texture',
  'soil ph',
  'wind',
  'maritime',
  'pollution',
  'poornutrition',
  'edible part and use', // TODO Appears in practicalplants.org MediaWiki API but missing in our data.
  'material use notes',
  'PFAF material use notes',
  'material part and use', // TODO Appears in practicalplants.org MediaWiki API but missing in our data.
  'medicinal part and use', // TODO Appears in practicalplants.org MediaWiki API but missing in our data.
  'toxic parts', // TODO Looks useful, special format
  'functions',
  'shelter', // TODO Looks useful, little used, special format
  'forage', // TODO Looks useful, little used, special format
  'propagation notes',
  'PFAF propagation notes',
  'seed requires stratification',
  'seed dormancy depth', // TODO Looks useful, little used
  'seed requires scarification', // TODO Looks useful, little used
  'seed requires smokification', // TODO Looks useful, little used
  'rootstocks',
  'cultivation notes',
  'PFAF cultivation notes',
  'crops', // TODO Looks useful, little used, special format
  'interactions',
  'botanical references',
  'material uses references',
  'range',
  'habitat', // TODO Maybe information could be parsed from the free-form text.
  'enabled',
  'title irregular',
  'common',
  'soil water retention',
  'medicinal use notes',
  'toxicity notes',
  'grow from',
  'germination details',
  'cultivation',
  'edible uses references',
  'medicinal uses references',
  'mature measurement unit',
  'pollinators',
  'edible use notes',
  'PFAF edible use notes',
  'PFAF medicinal use notes',
  'override summary',
  'ecosystem niche',
  'problems',
  'PFAF toxicity notes',
  'infraspecific epithet',
  'cultivar of groups',
  'cultivar epithet',
  'cultivar group epithet',
  'life references',
  'subspecies',
  'cultivar groups',
  'cutting type',
  'cutting details',
  'problem notes',
  'salinity',
  'fertility',
  'propagation',
  'common use description',
  'flower colour',
  'common habit description',
  'ungrouped cultivars',
  'functions notes',
  'botanical description',
  'crop notes',
  'classification references',
  'environmental references',
  'native range',
  'native environment', // TODO Looks useful, little used, free-formish
  'ecosystems references',
  'uses intro',
  'seed saving details',
  'root zone',
  'taxonomic rank',
  'functions as', // TODO Duplicate with 'functions', these should probably be combined?
  'shelter notes',
  'forage notes',
  'material uses', // TODO Looks useful, little used
  'heat zone', // TODO Looks useful, little used
  'bulb type', // TODO Looks useful, little used
  'graft rootstock', // TODO Looks useful, little used
  'edible parts', // TODO Looks useful, little used
  'edible uses', // TODO Looks useful, little used
  'show cultivar group',
  'cultivar group',
  'is a variety',
  'variety type',
  'cultivar name',
  'cultivar of',
  'variety name',
  'variety of',
  'subspecies name',
  'subspecies of',
  'summary',
  'cultivar group of',
  'seed stratification instructions',
  'graft details',
  'bulb details',
  'subspecific epithet',
  'cultivar notes',
  ''
];

/**
 * Looking at raw practicalplants.org MediaWiki data it seems that every property
 * is either a string or an array of objects, but then a string is sometimes an
 * array coded in CSV-format. This variable includes both types of arrays.
 */
const ARRAY_PROPERTIES = [
  'soil texture',
  'soil ph',
  'soil water retention',
  'ecosystem niche',
  'life cycle',
  'pollinators',
  'grow from',
  'cutting type',
  'fertility',
  'functions',
  'shelter',
  'forage',
  'crops',
  'grow from',
  'life references',
  'subspecies',
  'cultivar groups',
  'ungrouped cultivars',
  'environmental references',
  'native range',
  'functions as'
];

/*
 * Values that appear in raw practicalplants.org data.
 */
const BOOLEAN_VALUES = ['No', 'False', 'Yes', 'True'];
const HARDINESS_ZONE_VALUES = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '12'];
const SOIL_TEXTURE_VALUES = ['sandy', 'loamy', 'clay', 'heavy clay'];
const SOIL_PH_VALUES = [
  'very acid',
  'acid',
  'neutral',
  'alkaline',
  'very alkaline'
];
const SOIL_WATER_RETENTION_VALUES = ['well drained', 'moist', 'wet'];
const SHADE_VALUES = [
  'no shade',
  'light shade',
  'partial shade',
  'permanent shade',
  'permanent deep shade'
];
const SUN_VALUES = ['indirect sun', 'partial sun', 'full sun'];
const WATER_VALUES = ['low', 'moderate', 'high', 'aquatic'];
const DROUGHT_VALUES = ['dependent', 'tolerant', 'intolerant'];
const ECOSYSTEM_NICHE_VALUES = [
  'Canopy',
  'Climber',
  'Secondary canopy',
  'Soil surface',
  'Climber',
  'Shrub',
  'Herbaceous',
  'Rhizosphere'
];
const LIFE_CYCLE_VALUES = ['perennial', 'annual', 'biennial'];
const HERBACEOUS_OR_WOODY_VALUES = ['herbaceous', 'woody', ''];
const DECIDUOUS_OR_EVERGREEN_VALUES = ['deciduous', 'evergreen', ''];
const GROWTH_RATE_VALUES = ['slow', 'moderate', 'vigorous'];
const MATURE_MEASUREMENT_UNIT_VALUES = ['meters', 'metres', 'feet'];
const MATURE_HEIGHT_VALUES = [ '3.5',
  '1',
  '2',
  '45',
  '30',
  '15',
  '36',
  '20',
  '25',
  '75',
  '60',
  '50',
  '35',
  '40',
  '0.6',
  '0.1',
  '4',
  '5',
  '2.4',
  '3',
  '0.9',
  '8',
  '12',
  '9',
  '6',
  '0.45',
  '1.2',
  '10',
  '21',
  '4.5',
  '0.2',
  '0.3',
  '0.75',
  '0.15',
  '2.5',
  '1.5',
  '1.4',
  '0.8',
  '0.5',
  '7',
  '7.5',
  '13.5',
  '0.25',
  '1.8',
  '0.7',
  '0.4',
  '5 - 12',
  '0.12',
  '0.35',
  '18',
  '22',
  '1.3',
  '0.22',
  '0.05',
  '0.18',
  '0.08',
  '24',
  '0.02',
  '2.7',
  '3.6',
  '5.4',
  '33',
  '7.25',
  '5.5',
  '1.7',
  '1.6',
  '4+',
  '2.25',
  '55',
  '0.04',
  '13',
  '0.85',
  '0.01',
  '0',
  '1.25',
  '0.55',
  '0.07',
  '0.03',
  '65',
  '8-10',
  '23',
  '1.5 - 2',
  '0.65',
  '6 - 8',
  '110',
  '90',
  '14',
  '16',
  '70',
  '0.13' ];
const MATURE_WIDTH_VALUES = [ '3',
  '1',
  '15',
  '5',
  '10',
  '8',
  '6',
  '4',
  '0.8',
  '0.5',
  '2',
  '0.6',
  '12',
  '0.45',
  '0.4',
  '0.3',
  '1.5',
  '0.15',
  '2.5',
  '0.25',
  '0.08',
  '0.12',
  '0.1',
  '0.2',
  '0.05',
  '0.75',
  '0.04',
  '0.7',
  '1.2',
  '1.8',
  '3.5',
  '0.9',
  '18',
  '9',
  '20',
  '0.35',
  '4.5',
  '7',
  '25',
  '0.23',
  '1.25',
  '1.6',
  '0',
  '30',
  '7.5',
  '13',
  '0.01' ];
const FLOWER_TYPE_VALUES = ['hermaphrodite', 'monoecious', 'dioecious'];
const POLLINATORS_VALUES = [
  'Insects',
  'Wind',
  'Bees',
  'Flies',
  'Self',
  'Beetles',
  'Lepidoptera',
  'Bats',
  'Moths',
  'insects',
  'wind',
  'lepidoptera',
  'birds',
  'Apomictic',
  'Bees. self',
  'Apomyctic',
  'Slugs',
  'Snails',
  'Hover-flies',
  'Cleistogamous',
  'Wasps',
  'Water',
  'Midges',
  'Birds',
  'Flies and small bees',
  'Bees. lepidoptera',
  'Diptera',
  'Cleistogomous',
  'Butterflies',
  'Hoverflies',
  'Lepdioptera',
  'Apomixy',
  'Bumblebees',
  'Insect',
  'Humble bees',
  'Cleistogamy',
  'Wind-blown sand',
  'Flies lepidoptera',
  'Cleistogomy',
  'Self. Occasionally flies',
  'Insects? Self',
  'Sunbirds',
  'Self. Occasionally bees',
  'Carrion flies',
  'Self?',
  'Hand',
  'Dryoptera',
  'Hymenoptera'
];
const FUNCTIONS_VALUES = [
  'Nitrogen fixer',
  'Ground cover',
  'Hedge',
  'Windbreak',
  'Pioneer',
  'Nitrogen Fixer',
  'Earth stabiliser',
  'Green manure',
  'Repellant',
  'Soil builder',
  'Rootstock',
  'Biogenic Decalcifier/Pioneer Species',
  'Phytoremediation',
  'Bee attractor',
  'Soil conditioner',
  'Pest Repellent'
];
const GROW_FROM_VALUES = [
  'seed',
  'cutting',
  'layering',
  'tuber',
  'suckers',
  'graft',
  'bulb'
];
const CUTTING_TYPE_VALUES = [
  'semi-ripe',
  'soft wood',
  'root',
  'hard wood',
  ''
];
const FERTILITY_VALUES = ['self fertile', 'self sterile'];
const ROOT_ZONE_VALUES = ['shallow', 'deep', 'surface'];
const FAMILY_VALUES = [
  'Acanthaceae',
  'Aceraceae',
  'Actinidiaceae',
  'Agavaceae',
  'Aizoaceae',
  'Alangiaceae',
  'Alismataceae',
  'Alliaceae',
  'Aloeaceae',
  'Alstroemeriaceae',
  'Amaranthaceae',
  'Amaryllidaceae',
  'Anacardiaceae',
  'Annonaceae',
  'Apocynaceae',
  'Aponogetonaceae',
  'Aquifoliaceae',
  'Araceae',
  'Araliaceae',
  'Araucariaceae',
  'Aristolochiaceae',
  'Asclepiadaceae',
  'Asparagaceae',
  'Asphodelaceae',
  'Asteliaceae',
  'Asteraceae',
  'Atherospermataceae',
  'Balsaminaceae',
  'Basellaceae',
  'Begoniaceae',
  'Berberidaceae',
  'Betulaceae',
  'Bignoniaceae',
  'Blechnaceae',
  'Boraginaceae',
  'Brassicaceae',
  'Bromeliaceae',
  'Buddleiaceae',
  'Burseraceae',
  'Butomaceae',
  'Buxaceae',
  'Cabombaceae',
  'Cactaceae',
  'Callitrichaceae',
  'Calochortaceae',
  'Calycanthaceae',
  'Calyceraceae',
  'Campanulaceae',
  'Cannabidaceae',
  'Cannaceae',
  'Capparidaceae',
  'Caprifoliaceae',
  'Caryophyllaceae',
  'Casuarinaceae',
  'Celastraceae',
  'Cephalotaxaceae',
  'Ceratophyllaceae',
  'Cercidiphyllaceae',
  'Chenopodiaceae',
  'Chloranthaceae',
  'Cistaceae',
  'Clethraceae',
  'Cneoraceae',
  'Colchicaceae',
  'Commelinaceae',
  'Compositae',
  'Convallariaceae',
  'Convolvulaceae',
  'Coriariaceae',
  'Cornaceae',
  'Corynocarpaceae',
  'Crassulaceae',
  'Cucurbitaceae',
  'Cunoniaceae',
  'Cupressaceae',
  'Cyatheaceae',
  'Cycadaceae',
  'Cynocrambaceae',
  'Cyperaceae',
  'Cyrillaceae',
  'Daphniphyllaceae',
  'Datiscaceae',
  'Diapensiaceae',
  'Dicksoniaceae',
  'Dioscoreaceae',
  'Dipsacaceae',
  'Droseraceae',
  'Dryopteridaceae',
  'Ebenaceae',
  'Ehretiaceae',
  'Elaeagnaceae',
  'Elaeocarpaceae',
  'Empetraceae',
  'Epacridaceae',
  'Ephedraceae',
  'Equisetaceae',
  'Ericaceae',
  'Eriocaulaceae',
  'Escalloniaceae',
  'Eucommiaceae',
  'Eucryphiaceae',
  'Euphorbiaceae',
  'Eupomatiaceae',
  'Eupteleaceae',
  'Euryalaceae',
  'Fagaceae',
  'Flacourtiaceae',
  'Fumariaceae',
  'Funkiaceae',
  'Garryaceae',
  'Gentianaceae',
  'Geraniaceae',
  'Gesneriaceae',
  'Ginkgoaceae',
  'Gleicheniaceae',
  'Globulariaceae',
  'Goodeniaceae',
  'Gramineae',
  'Grossulariaceae',
  'Gunneraceae',
  'Haemodoraceae',
  'Haloragidaceae',
  'Hamamelidaceae',
  'Hemerocallidaceae',
  'Hippocastanaceae',
  'Hippuridaceae',
  'Hyacinthaceae',
  'Hydrangeaceae',
  'Hydrocharitaceae',
  'Hydrophyllaceae',
  'Hypericaceae',
  'Hypoxidaceae',
  'Illiciaceae',
  'Iridaceae',
  'Juglandaceae',
  'Juncaceae',
  'Juncaginaceae',
  'Labiatae',
  'Lamiaceae',
  'Lardizabalaceae',
  'Lauraceae',
  'Leguminosae',
  'Leitneriaceae',
  'Lemnaceae',
  'Lentibulariaceae',
  'Liliaceae',
  'Limnanthaceae',
  'Linaceae',
  'Loasaceae',
  'Loganiaceae',
  'Lomandraceae',
  'Loranthaceae',
  'Lycopodiaceae',
  'Lythraceae',
  'Magnoliaceae',
  'Malpighiaceae',
  'Malvaceae',
  'Marrattiaceae',
  'Marsileaceae',
  'Martyniaceae',
  'Melanthiaceae',
  'Melastomataceae',
  'Meliaceae',
  'Melianthaceae',
  'Menispermaceae',
  'Menyanthaceae',
  'Misodendraceae',
  'Molluginaceae',
  'Monimiaceae',
  'Moraceae',
  'Morinaceae',
  'Musaceae',
  'Myoporaceae',
  'Myricaceae',
  'Myrsinaceae',
  'Myrtaceae',
  'Najadaceae',
  'Nelumbonaceae',
  'Nyctaginaceae',
  'Nymphaeaceae',
  'Nyssaceae',
  'Oenotheraceae',
  'Oleaceae',
  'Onagraceae',
  'Onocleaceae',
  'Ophioglossaceae',
  'Orchidaceae',
  'Orobanchaceae',
  'Osmundaceae',
  'Oxalidaceae',
  'Paeoniaceae',
  'Palmae',
  'Papaveraceae',
  'Parmeliaceae',
  'Parnassiaceae',
  'Passifloraceae',
  'Pedaliaceae',
  'Philesiaceae',
  'Phormiaceae',
  'Phrymaceae',
  'Phytolaccaceae',
  'Pinaceae',
  'Pistaciaceae',
  'Pittosporaceae',
  'Plantaginaceae',
  'Platanaceae',
  'Plumbaginaceae',
  'Podocarpaceae',
  'Podophyllaceae',
  'Polemoniaceae',
  'Polygalaceae',
  'Polygonaceae',
  'Polypodiaceae',
  'Polytrichaceae',
  'Pontederiaceae',
  'Portulacaceae',
  'Potamogetonaceae',
  'Primulaceae',
  'Proteaceae',
  'Pteridaceae',
  'Punicaceae',
  'Pyrolaceae',
  'Rafflesiaceae',
  'Ranunculaceae',
  'Resedaceae',
  'Restoniaceae',
  'Rhamnaceae',
  'Rosaceae',
  'Rubiaceae',
  'Ruscaceae',
  'Rutaceae',
  'Salicaceae',
  'Santalaceae',
  'Sapindaceae',
  'Sapotaceae',
  'Sargentodoxaceae',
  'Sarraceniaceae',
  'Saururaceae',
  'Saxifragaceae',
  'Schisandraceae',
  'Sciadoptyaceae',
  'Scrophulariaceae',
  'Selaginellaceae',
  'Simaroubaceae',
  'Smilacaceae',
  'Solanaceae',
  'Sparganiaceae',
  'Sphagnaceae',
  'Staphyleaceae',
  'Sterculiaceae',
  'Styracaceae',
  'Symplocaceae',
  'Tamaricaceae',
  'Taxaceae',
  'Taxodiaceae',
  'Tecophilaeaceae',
  'Theaceae',
  'Thelypteridaceae',
  'Thymelaeaceae',
  'Tiliaceae',
  'Trapaceae',
  'Tricyrtidaceae',
  'Trilliaceae',
  'Tropaeolaceae',
  'Turneraceae',
  'Typhaceae',
  'Ulmaceae',
  'Umbelliferae',
  'Urticaceae',
  'Uvulariaceae',
  'Valerianaceae',
  'Verbenaceae',
  'Violaceae',
  'Viscaceae',
  'Vitaceae',
  'Winteraceae',
  'Xanthorrhoeaceae',
  'Xyridaceae',
  'Zannichelliaceae',
  'Zingiberaceae',
  'Zosteraceae',
  'Zygophyllaceae'
];
const GENUS_VALUES = [
  'Abelia',
  'Abelmoschus',
  'Abies',
  'Abobra',
  'Abronia',
  'Abutilon',
  'Acacia',
  'Acaenia',
  'Acalypha',
  'Acanthus',
  'Acca',
  'Acer',
  'Achillea',
  'Achnatherum',
  'Achyranthes',
  'Acinos',
  'Aciphylla',
  'Aconitum',
  'Acorus',
  'Acourtia',
  'Acrotriche',
  'Actaea',
  'Actinea',
  'Actinidia',
  'Adenophora',
  'Adenostoma',
  'Adesmia',
  'Adiantum',
  'Adina',
  'Adonis',
  'Aegilops',
  'Aegopodium',
  'Aesculus',
  'Aethusa',
  'Agalinis',
  'Agapanthus',
  'Agastache',
  'Agathis',
  'Agave',
  'Ageratina',
  'Ageratum',
  'Agoseris',
  'Agrimonia',
  'Agriophyllum',
  'Agropyron',
  'Agrostemma',
  'Agrostis',
  'Ailanthus',
  'Aizoon',
  'Ajuga',
  'Akebia',
  'Alangium',
  'Albizia',
  'Albuca',
  'Alcea',
  'Alchemilla',
  'Aletris',
  'Aleurites',
  'Alhagi',
  'Alisma',
  'Alkanna',
  'Alliaria',
  'Allium',
  'Alnus',
  'Aloe',
  'Alopecurus',
  'Aloysia',
  'Alstroemeria',
  'Althaea',
  'Amaranthus',
  'Ambrosia',
  'Amelanchier',
  'Amelasorbus',
  'Ammannia',
  'Ammi',
  'Ammophila',
  'Amomyrtus',
  'Amorpha',
  'Amorphophallus',
  'Ampelodesmos',
  'Ampelopsis',
  'Amphicarpaea',
  'Amsinckia',
  'Amyema',
  'Anacamptis',
  'Anacyclus',
  'Anagallis',
  'Anaphalis',
  'Anchusa',
  'Andromeda',
  'Andropogon',
  'Androsace',
  'Androstephium',
  'Anemarrhena',
  'Anemone',
  'Anemonella',
  'Anemopsis',
  'Anethum',
  'Angelica',
  'Angiopteris',
  'Angophora',
  'Anredera',
  'Antennaria',
  'Anthemis',
  'Anthoxanthum',
  'Anthriscus',
  'Anthyllis',
  'Antirrhinum',
  'Aphananthe',
  'Aphanes',
  'Apios',
  'Apium',
  'Aplectrum',
  'Apocynum',
  'Aponogeton',
  'Aquilegia',
  'Arabidopsis',
  'Arabis',
  'Arachis',
  'Aralia',
  'Araucaria',
  'Araujia',
  'Arbutus',
  'Arctium',
  'Arctostaphylos',
  'Ardisia',
  'Arenaria',
  'Argemone',
  'Argyranthemum',
  'Arisaema',
  'Arisarum',
  'Aristolochia',
  'Aristotelia',
  'Arjona',
  'Armeria',
  'Armoracia',
  'Arnebia',
  'Arnica',
  'Aronia',
  'Arracacia',
  'Artemisia',
  'Arthrocnemum',
  'Arthromeris',
  'Arthropodium',
  'Arum',
  'Arundinaria',
  'Arundinella',
  'Arundo',
  'Asarum',
  'Asclepias',
  'Asimina',
  'Aspalathus',
  'Asparagus',
  'Asperula',
  'Asphodeline',
  'Asphodelus',
  'Aspidistra',
  'Aspidosperma',
  'Asplenium',
  'Astelia',
  'Aster',
  'Astilbe',
  'Astragalus',
  'Astrantia',
  'Astrebla',
  'Astroloma',
  'Asyneuma',
  'Athamantha',
  'Atherosperma',
  'Athrotaxis',
  'Athyrium',
  'Atractylis',
  'Atractylodes',
  'Atraphaxis',
  'Atriplex',
  'Atropa',
  'Aubrietia',
  'Aucuba',
  'Aurinia',
  'Avena',
  'Azara',
  'Azorella',
  'Azorina',
  'Babiana',
  'Baccharis',
  'Backhousia',
  'Baeckea',
  'Ballota',
  'Balsamorhiza',
  'Bambusa',
  'Banksia',
  'Baptisia',
  'Barbarea',
  'Basella',
  'Bassia',
  'Bauhinia',
  'Beckmannia',
  'Begonia',
  'Beilschmiedia',
  'Belamcanda',
  'Bellis',
  'Benincasa',
  'Berberidopsis',
  'Berberis',
  'Berchemia',
  'Bergenia',
  'Berula',
  'Beta',
  'Betula',
  'Bidens',
  'Billardiera',
  'Blackstonia',
  'Blechnum',
  'Bletilla',
  'Bloomeria',
  'Bobartia',
  'Boehmeria',
  'Boenninghausenia',
  'Boerhavia',
  'Bolax',
  'Bomarea',
  'Bongardia',
  'Boopsis',
  'Borago',
  'Borinda',
  'Boronia',
  'Botrychium',
  'Bouteloua',
  'Brachychiton',
  'Brachyglottis',
  'Brachyloma',
  'Bracyloma',
  'Brahea',
  'Brasenia',
  'Brassica',
  'Brodiaea',
  'Bromus',
  'Broussonetia',
  'Bryonia',
  'Buddleia',
  'Buglossoides',
  'Bulbinella',
  'Bulbinopsis',
  'Bulbophyllum',
  'Bumelia',
  'Bunchosia',
  'Bunias',
  'Bunium',
  'Bupleurum',
  'Burchardia',
  'Bursaria',
  'Butia',
  'Butomus',
  'Buxus',
  'Cacalia',
  'Caesalpinia',
  'Caesia',
  'Cakile',
  'Calamintha',
  'Calandrinia',
  'Calceolaria',
  'Calendula',
  'Calicotome',
  'Calla',
  'Callicarpa',
  'Callicoma',
  'Calligonum',
  'Callirhoe',
  'Callistemon',
  'Callitriche',
  'Callitris',
  'Calluna',
  'Calocedrus',
  'Calochortus',
  'Caltha',
  'Calycanthus',
  'Calypso',
  'Calystegia',
  'Camassia',
  'Camelina',
  'Camellia',
  'Campanula',
  'Camphorosma',
  'Campsis',
  'Canarium',
  'Canna',
  'Cannabis',
  'Capparis',
  'Capsella',
  'Capsicum',
  'Caragana',
  'Cardamine',
  'Cardaria',
  'Cardiocrinum',
  'Cardiospermum',
  'Carduus',
  'Carex',
  'Carlina',
  'Carpesium',
  'Carpinus',
  'Carpobrotus',
  'Carthamnus',
  'Carum',
  'Carya',
  'Cassinia',
  'Cassiope',
  'Cassythia',
  'Castanea',
  'Castanopsis',
  'Castanospermum',
  'Castilleja',
  'Casuarina',
  'Catabrosa',
  'Catalpa',
  'Caucalis',
  'Caulanthus',
  'Caulophyllum',
  'Cautleya',
  'Cavendishia',
  'Ceanothus',
  'Cedronella',
  'Cedrus',
  'Celastrus',
  'Celosia',
  'Celtis',
  'Centaurea',
  'Centaurium',
  'Centella',
  'Centipeda',
  'Centranthus',
  'Centrosema',
  'Cephalanthus',
  'Cephalaria',
  'Cephalotaxus',
  'Cerastium',
  'Ceratonia',
  'Ceratophyllum',
  'Ceratostigma',
  'Cercidiphyllum',
  'Cercis',
  'Cercocarpus',
  'Ceroxylon',
  'Cetraria',
  'Chaenactis',
  'Chaenomeles',
  'Chaerophyllum',
  'Chamaecrista',
  'Chamaecyparis',
  'Chamaedaphne',
  'Chamaelirium',
  'Chamaemelum',
  'Chamaerops',
  'Chamaesaracha',
  'Chasmanthium',
  'Cheilanthes',
  'Chelidonium',
  'Chelone',
  'Chenopodium',
  'Chesneya',
  'Chiliotrichum',
  'Chilopsis',
  'Chimaphila',
  'Chimonanthus',
  'Chimonobambusa',
  'Chionanthus',
  'Chionographis',
  'Chloranthus',
  'Chlorogalum',
  'Choisya',
  'Chondrilla',
  'Chorispora',
  'Chrozophora',
  'Chrysanthemum',
  'Chrysolepis',
  'Chrysosplenium',
  'Chrysothamnus',
  'Chusquea',
  'Cibotium',
  'Cicer',
  'Cicerbita',
  'Cichorium',
  'Cicuta',
  'Cimicifuga',
  'Cinna',
  'Cinnamomum',
  'Circaea',
  'Cirsium',
  'Cistus',
  'Citrofortunella',
  'Citroncirus',
  'Citrullus',
  'Citrus',
  'Cladium',
  'Cladrastis',
  'Clarkia',
  'Claytonia',
  'Clematis',
  'Cleome',
  'Clerodendrum',
  'Clethra',
  'Cliftonia',
  'Clinopodium',
  'Clintonia',
  'Cneorum',
  'Cnicus',
  'Cnidium',
  'Coccinia',
  'Cocculus',
  'Cochlearia',
  'Codonopsis',
  'Coelopleurum',
  'Coix',
  'Colchicum',
  'Coleus',
  'Colletia',
  'Collinsonia',
  'Coluria',
  'Colutea',
  'Comandra',
  'Commelina',
  'Commersonia',
  'Comptonia',
  'Conandron',
  'Conanthera',
  'Condalia',
  'Coniogramme',
  'Conioselinum',
  'Conium',
  'Conopodium',
  'Conradina',
  'Conringia',
  'Consolida',
  'Convallaria',
  'Convolvulus',
  'Conyza',
  'Coprosma',
  'Coptis',
  'Corallorhiza',
  'Corchorus',
  'Cordyline',
  'Corema',
  'Coreopsis',
  'Coriandrum',
  'Coriaria',
  'Cornus',
  'Corokia',
  'Coronilla',
  'Coronopus',
  'Correa',
  'Corrigiola',
  'Cortaderia',
  'Corydalis',
  'Corylus',
  'Corynocarpus',
  'Cosmos',
  'Cotinus',
  'Cotoneaster',
  'Cotula',
  'Cousinia',
  'Cowania',
  'Crambe',
  'Crataegomespilus',
  'Crataegus',
  'Crepis',
  'Crinum',
  'Crithmum',
  'Crocosmia',
  'Crocus',
  'Crotalaria',
  'Cruciata',
  'Cryptomeria',
  'Cryptotaenia',
  'Cucubalus',
  'Cucumis',
  'Cucurbita',
  'Cudrania',
  'Cuminum',
  'Cunila',
  'Cunninghamia',
  'Cuphea',
  'Cupressocyparis',
  'Cupressus',
  'Cuscuta',
  'Cyananthus',
  'Cyanella',
  'Cyathea',
  'Cyathodes',
  'Cycas',
  'Cyclamen',
  'Cyclanthera',
  'Cyclea',
  'Cycloloma',
  'Cyclospermum',
  'Cydonia',
  'Cymbalaria',
  'Cymbonotus',
  'Cymopterus',
  'Cynanchum',
  'Cynara',
  'Cynodon',
  'Cynoglossum',
  'Cyperus',
  'Cyphomandra',
  'Cypripedium',
  'Cyrilla',
  'Cyrtanthus',
  'Cyrtomium',
  'Cystopteris',
  'Cytinus',
  'Cytisus',
  'Dacrycarpus',
  'Dacrydium',
  'Dactylis',
  'Dactyloctenium',
  'Dactylorhiza',
  'Dahlia',
  'Dalbergia',
  'Dalea',
  'Damasonium',
  'Daphne',
  'Daphniphyllum',
  'Darmera',
  'Dasylirion',
  'Datisca',
  'Datura',
  'Daucus',
  'Daviesia',
  'Debregeasia',
  'Decaisnea',
  'Decemium',
  'Deinanthe',
  'Delphinium',
  'Dendranthema',
  'Dendrobium',
  'Dendrostellera',
  'Dentaria',
  'Deschampsia',
  'Descurainia',
  'Desfontainia',
  'Desmanthus',
  'Desmodium',
  'Desmoschoenus',
  'Deutzia',
  'Dianella',
  'Dianthus',
  'Dicentra',
  'Dichelachne',
  'Dichelostemma',
  'Dichondra',
  'Dichopogon',
  'Dichroa',
  'Dicksonia',
  'Dicliptera',
  'Dicoria',
  'Dictamnus',
  'Diervilla',
  'Digitalis',
  'Digitaria',
  'Dioscorea',
  'Diospyros',
  'Dipcadi',
  'Diphylleia',
  'Diplotaxis',
  'Diploterigium',
  'Dipploglottis',
  'Dipsacus',
  'Dirca',
  'Disphyma',
  'Disporum',
  'Distylium',
  'Dittrichia',
  'Docynia',
  'Dodecatheon',
  'Dodonaea',
  'Dorema',
  'Doronicum',
  'Draba',
  'Dracocephalum',
  'Drepanostachyum',
  'Drimys',
  'Drosera',
  'Dryas',
  'Drymaria',
  'Dryopteris',
  'Duchesnea',
  'Dudleya',
  'Dysosma',
  'Dysoxylum',
  'Ecballium',
  'Echinacea',
  'Echinochloa',
  'Echinocystis',
  'Echinophora',
  'Echinops',
  'Echium',
  'Eclipta',
  'Edgeworthia',
  'Ehretia',
  'Eichhornia',
  'Elaeagnus',
  'Elaeocarpus',
  'Elatostema',
  'Eleocharis',
  'Eleusine',
  'Eleutherococcus',
  'Elodea',
  'Elsholtzia',
  'Elymus',
  'Elytrigia',
  'Emex',
  'Emilia',
  'Eminium',
  'Empetrum',
  'Encelia',
  'Enchylaena',
  'Ensete',
  'Entelea',
  'Ephedra',
  'Epifagus',
  'Epigaea',
  'Epilobium',
  'Epimedium',
  'Equisetum',
  'Eragrostis',
  'Erechtites',
  'Eremophila',
  'Eremurus',
  'Erica',
  'Ericameria',
  'Erigenia',
  'Erigeron',
  'Eriobotrya',
  'Eriocaulon',
  'Eriodictyon',
  'Eriogonum',
  'Eriophorum',
  'Eriophyton',
  'Erodium',
  'Erophila',
  'Eruca',
  'Erucaria',
  'Eryngium',
  'Erysimum',
  'Erythrina',
  'Erythronium',
  'Escallonia',
  'Eschscholzia',
  'Eucalyptus',
  'Euchresta',
  'Eucommia',
  'Eucryphia',
  'Euodia',
  'Euonymus',
  'Eupatorium',
  'Euphorbia',
  'Euphrasia',
  'Eupomatia',
  'Euptelea',
  'Eurya',
  'Euryale',
  'Euscaphis',
  'Eustrephus',
  'Exocarpus',
  'Fabiana',
  'Fagopyrum',
  'Fagus',
  'Fallopia',
  'Fallugia',
  'Farfugium',
  'Fargesia',
  'Fedia',
  'Ferula',
  'Festuca',
  'Fibigia',
  'Ficus',
  'Filipendula',
  'Fimbristylis',
  'Firmiana',
  'Fitzroya',
  'Foeniculum',
  'Fontanesia',
  'Forestiera',
  'Forsythia',
  'Fortunella',
  'Fragaria',
  'Frasera',
  'Fraxinus',
  'Fremontodendron',
  'Fritillaria',
  'Fuchsia',
  'Fumaria',
  'Gagea',
  'Gaillardia',
  'Galactites',
  'Galanthus',
  'Galax',
  'Galega',
  'Galeopsis',
  'Galinsoga',
  'Galium',
  'Garrya',
  'Gastrodia',
  'Gaultheria',
  'Gaylussacia',
  'Geijera',
  'Geitonoplesium',
  'Gelsemium',
  'Genista',
  'Gentiana',
  'Gentianella',
  'Geocaulon',
  'Geranium',
  'Gerbera',
  'Geum',
  'Gevuina',
  'Gillenia',
  'Gingidia',
  'Ginkgo',
  'Girardiana',
  'Gladiolus',
  'Glaucium',
  'Glaux',
  'Glechoma',
  'Gleditsia',
  'Glehnia',
  'Globularia',
  'Glochidion',
  'Glyceria',
  'Glycine',
  'Glycyrrhiza',
  'Glyptostrobus',
  'Gnaphalium',
  'Goodenia',
  'Goodyera',
  'Gratiola',
  'Greigia',
  'Grevillea',
  'Grewia',
  'Grindelia',
  'Griselinia',
  'Guizotia',
  'Gundelia',
  'Gunnera',
  'Gutierrezia',
  'Gymnadenia',
  'Gymnocladus',
  'Gynandriris',
  'Gynatrix',
  'Gynostemma',
  'Gynura',
  'Gypsophila',
  'Habenaria',
  'Hackelia',
  'Hakea',
  'Halenia',
  'Halerpestes',
  'Halesia',
  'Halimione',
  'Halimodendron',
  'Haloxylon',
  'Hamamelis',
  'Haplopappus',
  'Hardenbergia',
  'Hebe',
  'Hedeoma',
  'Hedera',
  'Hedychium',
  'Hedysarum',
  'Heimia',
  'Heldreichia',
  'Helenium',
  'Helianthemum',
  'Helianthus',
  'Helichrysum',
  'Heliotropium',
  'Helleborus',
  'Helwingia',
  'Hemerocallis',
  'Hemiphragma',
  'Hemiptelea',
  'Hemizonia',
  'Hepatica',
  'Heracleum',
  'Herniaria',
  'Herpetospermum',
  'Hesperaloe',
  'Hesperantha',
  'Hesperis',
  'Hesperocallis',
  'Heteropappus',
  'Heuchera',
  'Hibiscus',
  'Hieracium',
  'Hierochloe',
  'Hilaria',
  'Himalayacalamus',
  'Hippophae',
  'Hippuris',
  'Hirschfeldia',
  'Hoffmannseggia',
  'Hoheria',
  'Holboellia',
  'Holodiscus',
  'Hololeion',
  'Homoranthus',
  'Honckenya',
  'Hordeum',
  'Hosta',
  'Hottonia',
  'Houttuynia',
  'Hovenia',
  'Humulus',
  'Hyacinthoides',
  'Hyacinthus',
  'Hydrangea',
  'Hydrastis',
  'Hydrilla',
  'Hydrocotyle',
  'Hydrophyllum',
  'Hymenanthera',
  'Hymenopappus',
  'Hymenoxys',
  'Hyoscyamus',
  'Hypericum',
  'Hypochoeris',
  'Hypoxis',
  'Hyssopus',
  'Iberis',
  'Idesia',
  'Ilex',
  'Illicium',
  'Impatiens',
  'Imperata',
  'Incarvillea',
  'Indigofera',
  'Indocalamus',
  'Inula',
  'Ipomoea',
  'Ipomopsis',
  'Iris',
  'Isatis',
  'Isodon',
  'Isopogon',
  'Itea',
  'Iva',
  'Ixeris',
  'Jasminum',
  'Jeffersonia',
  'Jovibarba',
  'Jubaea',
  'Juglans',
  'Juncus',
  'Juniperus',
  'Jurinea',
  'Jussieva',
  'Justicia',
  'Kadsura',
  'Kalimeris',
  'Kalmia',
  'Kalopanax',
  'Kerria',
  'Keteleeria',
  'Kickxia',
  'Kinugasa',
  'Kirkophytum',
  'Knautia',
  'Knightia',
  'Kniphofia',
  'Koeleria',
  'Koelreuteria',
  'Kosteletzkya',
  'Kuhnia',
  'Kummerowia',
  'Kunzea',
  'Lablab',
  'Laburnum',
  'Lachnanthes',
  'Lactuca',
  'Lagarostrobus',
  'Lagenaria',
  'Lagerstroemia',
  'Lagochilus',
  'Lagoecia',
  'Lallemantia',
  'Lamium',
  'Lancea',
  'Lapageria',
  'Laportea',
  'Lapsana',
  'Lardizabala',
  'Laretia',
  'Larix',
  'Larrea',
  'Laser',
  'Laserpitium',
  'Lasthenia',
  'Lathyrus',
  'Laurelia',
  'Lavandula',
  'Lavatera',
  'Layia',
  'Ledebouriella',
  'Ledum',
  'Legousia',
  'Leibnitzia',
  'Leichhardtia',
  'Leitneria',
  'Lemna',
  'Lens',
  'Leontice',
  'Leontodon',
  'Leontopodium',
  'Leonurus',
  'Lepidium',
  'Lepidogrammitis',
  'Lepidosperma',
  'Lepidothamnus',
  'Leptocarpus',
  'Leptomeria',
  'Leptospermum',
  'Lespedeza',
  'Lesquerella',
  'Leucanthemum',
  'Leucas',
  'Leucocrinum',
  'Leucojum',
  'Leucopogon',
  'Leucothoe',
  'Leuzea',
  'Levisticum',
  'Lewisia',
  'Leycesteria',
  'Leymus',
  'Liatris',
  'Libocedrus',
  'Ligularia',
  'Ligusticum',
  'Ligustrum',
  'Lilaea',
  'Lilium',
  'Limnanthes',
  'Limonium',
  'Linaria',
  'Lindera',
  'Linnaea',
  'Linum',
  'Liparis',
  'Liquidambar',
  'Liriodendron',
  'Liriope',
  'Lissanthe',
  'Lithocarpus',
  'Lithospermum',
  'Litsea',
  'Livistona',
  'Lobelia',
  'Lobularia',
  'Lolium',
  'Lomandra',
  'Lomatium',
  'Lonicera',
  'Lophomyrtus',
  'Loropetalum',
  'Lotus',
  'Ludwigia',
  'Luma',
  'Lunaria',
  'Lupinus',
  'Luzula',
  'Lychnis',
  'Lycium',
  'Lycopersicon',
  'Lycopodium',
  'Lycopus',
  'Lycoris',
  'Lygeum',
  'Lygodesmia',
  'Lyonia',
  'Lyonsia',
  'Lysichiton',
  'Lysimachia',
  'Lythrum',
  'Maackia',
  'Macadamia',
  'Macleaya',
  'Maclura',
  'Macromeria',
  'Macrotomia',
  'Madia',
  'Magnolia',
  'Mahoberberis',
  'Mahonia',
  'Maianthemum',
  'Malus',
  'Malva',
  'Malvastrum',
  'Mandragora',
  'Marah',
  'Margyricarpus',
  'Marrubium',
  'Marsdenia',
  'Marsilea',
  'Marsippospermum',
  'Matricaria',
  'Matteuccia',
  'Matthiola',
  'Maytenus',
  'Mazus',
  'Meconopsis',
  'Medeola',
  'Medicago',
  'Meehania',
  'Megacarpaea',
  'Megacodon',
  'Melaleuca',
  'Melanthium',
  'Melastoma',
  'Melia',
  'Melianthus',
  'Melichrus',
  'Melicope',
  'Melicytus',
  'Melilotus',
  'Melissa',
  'Melittis',
  'Menispermum',
  'Mentha',
  'Mentzelia',
  'Menyanthes',
  'Menziesia',
  'Mercurialis',
  'Mertensia',
  'Mesembryanthemum',
  'Mespilus',
  'Metaplexis',
  'Metasequoia',
  'Metrosideros',
  'Meum',
  'Michelia',
  'Microcachrys',
  'Micromeria',
  'Microseris',
  'Microtis',
  'Milium',
  'Millettia',
  'Mimulus',
  'Mirabilis',
  'Miscanthus',
  'Misodendrum',
  'Mitchella',
  'Mitella',
  'Mollugo',
  'Momorialis',
  'Monarda',
  'Monardella',
  'Moneses',
  'Monizia',
  'Monolepis',
  'Monotoca',
  'Monotropa',
  'Montia',
  'Moraea',
  'Morina',
  'Morus',
  'Mosla',
  'Muehlenbeckia',
  'Muhlenbergia',
  'Musa',
  'Muscari',
  'Musineon',
  'Mycelis',
  'Myoporum',
  'Myosotis',
  'Myosoton',
  'Myriactis',
  'Myrica',
  'Myricaria',
  'Myriophyllum',
  'Myrrhis',
  'Myrsine',
  'Myrteola',
  'Myrtus',
  'Nabalus',
  'Nageia',
  'Najas',
  'Nandina',
  'Nannorrhops',
  'Narcissus',
  'Nardostachys',
  'Nasturtium',
  'Navarretia',
  'Neillia',
  'Nelumbo',
  'Nemopanthus',
  'Neolitsea',
  'Neomyrtus',
  'Nepeta',
  'Nerium',
  'Nertera',
  'Nicandra',
  'Nicotiana',
  'Nigella',
  'Nitraria',
  'Nothofagus',
  'Nothoscordum',
  null,
  'Nuphar',
  'Nymphaea',
  'Nymphoides',
  'Nyssa',
  'Ocimum',
  'Oemleria',
  'Oenanthe',
  'Oenothera',
  'Oldenlandia',
  'Olea',
  'Olearia',
  'Olneya',
  'Onobrychis',
  'Onoclea',
  'Ononis',
  'Onopordum',
  'Onosma',
  'Ophioglossum',
  'Ophiopogon',
  'Ophrys',
  'Oplopanax',
  'Opopanax',
  'Opuntia',
  'Orchis',
  'Oreomyrrhis',
  'Origanum',
  'Orixa',
  'Ornithogalum',
  'Ornithopus',
  'Orobanche',
  'Orogenia',
  'Orontium',
  'Orostachys',
  'Orthilia',
  'Orychophragmus',
  'Oryzopsis',
  'Osbeckia',
  'Osmanthus',
  'Osmorhiza',
  'Osmunda',
  'Osteomeles',
  'Ostrya',
  'Oxalis',
  'Oxydendrum',
  'Oxyria',
  'Oxytropis',
  'Pachyphragma',
  'Pachyrhizus',
  'Pachysandra',
  'Packera',
  'Paederia',
  'Paeonia',
  'Paliuris',
  'Panax',
  'Pancratium',
  'Panicum',
  'Papaver',
  'Parajubaea',
  'Parietaria',
  'Paris',
  'Parnassia',
  'Paronychia',
  'Parosella',
  'Parrotiopsis',
  'Parryella',
  'Parthenium',
  'Parthenocissus',
  'Passiflora',
  'Pastinaca',
  'Patrinia',
  'Paulownia',
  'Pectis',
  'Pedicularis',
  'Peganum',
  'Pelargonium',
  'Peltandra',
  'Peltaria',
  'Pennisetum',
  'Penstemon',
  'Pentachondra',
  'Pentaglottis',
  'Penthorum',
  'Peracarpa',
  'Peraphyllum',
  'Pericome',
  'Perideridia',
  'Perilla',
  'Periploca',
  'Perovskia',
  'Persea',
  'Persoonia',
  'Petasites',
  'Peteria',
  'Petroselinum',
  'Peucedanum',
  'Peumus',
  'Phacelia',
  'Phalaris',
  'Phaseolus',
  'Phellodendron',
  'Philadelphus',
  'Phillyrea',
  'Phleum',
  'Phlomis',
  'Phlox',
  'Phoenix',
  'Phoradendron',
  'Phormium',
  'Photinia',
  'Phragmites',
  'Phryma',
  'Phyla',
  'Phyllocladus',
  'Phyllospadix',
  'Phyllostachys',
  'Physaliastrum',
  'Physalis',
  'Physocarpus',
  'Phyteuma',
  'Phytolacca',
  'Picea',
  'Picrasma',
  'Picris',
  'Picrorhiza',
  'Pieris',
  'Pilosella',
  'Pimelea',
  'Pimpinella',
  'Pinckneya',
  'Pinellia',
  'Pinguicula',
  'Pinus',
  'Pistacia',
  'Pisum',
  'Pittosporum',
  'Plagianthus',
  'Plagiobothrys',
  'Planchonella',
  'Plantago',
  'Platanthera',
  'Platanus',
  'Platycarya',
  'Platycodon',
  'Platycrater',
  'Platystemon',
  'Plectranthus',
  'Pleioblastus',
  'Pleurospermum',
  'Plumbago',
  'Poa',
  'Podocarpium',
  'Podocarpus',
  'Podolepis',
  'Podophyllum',
  'Pogantherum',
  'Pogogyne',
  'Polemonium',
  'Polianthes',
  'Poliomintha',
  'Polygala',
  'Polygonatum',
  'Polygonum',
  'Polymnia',
  'Polypodium',
  'Polypogon',
  'Polyscias',
  'Polystichum',
  'Polytrichum',
  'Poncirus',
  'Pontederia',
  'Populus',
  'Portulaca',
  'Potamogeton',
  'Potentilla',
  'Prangos',
  'Pratia',
  'Prenanthes',
  'Primula',
  'Pringlea',
  'Prinsepia',
  'Proboscidea',
  'Prostanthera',
  'Protea',
  'Prumnopitys',
  'Prunella',
  'Prunus',
  'Pseudocydonia',
  'Pseudognaphalium',
  'Pseudolarix',
  'Pseudopanax',
  'Pseudosasa',
  'Pseudotsuga',
  'Pseudowintera',
  'Psidium',
  'Psophocarpus',
  'Psoralea',
  'Psychotria',
  'Ptelea',
  'Pteridium',
  'Pterocarya',
  'Pteroceltis',
  'Pterospora',
  'Pterostyrax',
  'Ptiloria',
  'Puccinellia',
  'Pueraria',
  'Pugionium',
  'Pulicaria',
  'Pulmonaria',
  'Pulsatilla',
  'Punica',
  'Puya',
  'Pycnanthemum',
  'Pyracantha',
  'Pyrocydonia',
  'Pyrola',
  'Pyronia',
  'Pyrrhopappus',
  'Pyrularia',
  'Pyrus',
  'Quercus',
  'Quillaja',
  'Ranunculus',
  'Raphanus',
  'Ratibida',
  'Reaumuria',
  'Rehmannia',
  'Reichardia',
  'Reineckia',
  'Reseda',
  'Rhagodia',
  'Rhamnella',
  'Rhamnus',
  'Rhaphiolepis',
  'Rhaponticum',
  'Rheum',
  'Rhexia',
  'Rhinanthus',
  'Rhodiola',
  'Rhododendron',
  'Rhus',
  'Rhynchosinapis',
  'Ribes',
  'Ricinus',
  'Ripogonum',
  'Robinia',
  'Rodgersia',
  'Rohdea',
  'Romanzoffia',
  'Romulea',
  'Rorippa',
  'Rosa',
  'Rubia',
  'Rubus',
  'Rudbeckia',
  'Rulingia',
  'Rumex',
  'Ruscus',
  'Ruta',
  'Sabal',
  'Sabatia',
  'Sagina',
  'Sagittaria',
  'Salicornia',
  'Salix',
  'Salsola',
  'Salvia',
  'Sambucus',
  'Samolus',
  'Sanguinaria',
  'Sanguisorba',
  'Sanicula',
  'Sanseviera',
  'Santalum',
  'Santolina',
  'Sapindus',
  'Sapium',
  'Saponaria',
  'Sarcobatus',
  'Sargentodoxa',
  'Sarracenia',
  'Sasa',
  'Sasaella',
  'Sasamorpha',
  'Sassafras',
  'Satureja',
  'Saururus',
  'Saussurea',
  'Saxifraga',
  'Scabiosa',
  'Scaevola',
  'Scandix',
  'Schinus',
  'Schisandra',
  'Schizomeria',
  'Schizophragma',
  'Sciadopitys',
  'Scilla',
  'Scirpus',
  'Scleranthus',
  'Scolymus',
  'Scopolia',
  'Scorpiurus',
  'Scorzonera',
  'Scrophularia',
  'Scutellaria',
  'Sebaea',
  'Secale',
  'Securidaca',
  'Securinega',
  'Sedum',
  'Selaginella',
  'Semiaquilegia',
  'Semiarundinaria',
  'Sempervivum',
  'Senecio',
  'Senna',
  'Sequoia',
  'Sequoiadendron',
  'Serenoa',
  'Serratula',
  'Sesamum',
  'Sesbania',
  'Seseli',
  'Sesuvium',
  'Setaria',
  'Shepherdia',
  'Sherardia',
  'Shibataea',
  'Sicyos',
  'Sidalcea',
  'Sideritis',
  'Siegesbeckia',
  'Silaum',
  'Silene',
  'Silphium',
  'Silybum',
  'Sinapis',
  'Sinofranchetia',
  'Sinomenium',
  'Siphonostegia',
  'Sison',
  'Sisymbrium',
  'Sisyrinchium',
  'Sium',
  'Skimmia',
  'Smilacena',
  'Smilax',
  'Smyrnium',
  'Solanum',
  'Soldanella',
  'Solidago',
  'Sonchus',
  'Sophora',
  'Sorbaria',
  'Sorbopyrus',
  'Sorbus',
  'Sorghum',
  'Sparaxis',
  'Sparganium',
  'Spartina',
  'Spartium',
  'Spergula',
  'Spergularia',
  'Sphagnum',
  'Spigelia',
  'Spinacia',
  'Spiraea',
  'Spiranthes',
  'Spirodela',
  'Sporobolus',
  'Stachys',
  'Stanleya',
  'Staphylea',
  'Stauntonia',
  'Stellaria',
  'Stellera',
  'Stephanandra',
  'Stephanomeria',
  'Stevia',
  'Stewartia',
  'Stilbocarpa',
  'Stillingia',
  'Stipa',
  'Stratiotes',
  'Streptopus',
  'Strobilanthes',
  'Stylophorum',
  'Styphelia',
  'Styrax',
  'Suaeda',
  'Succisa',
  'Swertia',
  'Sympholoma',
  'Symphoricarpos',
  'Symphytum',
  'Symplocarpus',
  'Symplocos',
  'Syncarpia',
  'Synurus',
  'Syringa',
  'Syzygium',
  'Tagetes',
  'Talinum',
  'Tamarix',
  'Tamus',
  'Tanacetum',
  'Taraxacum',
  'Taxodium',
  'Taxus',
  'Tellima',
  'Telopea',
  'Tephroseris',
  'Tephrosia',
  'Ternstroemia',
  'Tetragonia',
  'Tetrapanax',
  'Tetrastigma',
  'Teucrium',
  'Thalictrum',
  'Thamnocalamus',
  'Thapsia',
  'Thelesperma',
  'Theligonum',
  'Thelymitra',
  'Thelypteris',
  'Thermopsis',
  'Thladiantha',
  'Thlaspi',
  'Thuja',
  'Thujopsis',
  'Thymbra',
  'Thymus',
  'Thysanotus',
  'Tiarella',
  'Tigridia',
  'Tilia',
  'Tilingia',
  'Tinopsora',
  'Tithonia',
  'Tolmiea',
  'Toona',
  'Tordylium',
  'Torilis',
  'Torreya',
  'Trachelospermum',
  'Trachycarpus',
  'Trachymene',
  'Trachyspermum',
  'Trachystemon',
  'Tradescantia',
  'Tragopogon',
  'Trapa',
  'Tribulus',
  'Trichosanthes',
  'Tricyrtis',
  'Trientalis',
  'Trifolium',
  'Triglochin',
  'Trigonella',
  'Trigonotis',
  'Trilisa',
  'Trillium',
  'Triodia',
  'Triosteum',
  'Triphasia',
  'Tripsacum',
  'Tripterygium',
  'Trisetum',
  'Triteleia',
  'Triticosecale',
  'Triticum',
  'Tritonia',
  'Trochocarpa',
  'Trollius',
  'Tropaeolum',
  'Tsuga',
  'Tulbaghia',
  'Tulipa',
  'Tupeia',
  'Turnera',
  'Turritis',
  'Tussilago',
  'Tylophora',
  'Typha',
  'Ugni',
  'Ulex',
  'Ullucus',
  'Ulmus',
  'Umbellularia',
  'Umbilicus',
  'Uncaria',
  'Uniola',
  'Urceola',
  'Urginea',
  'Urospermum',
  'Urtica',
  'Utricularia',
  'Uvularia',
  'Vaccaria',
  'Vaccinium',
  'Valeriana',
  'Valerianella',
  'Vallisneria',
  'Veratrum',
  'Verbascum',
  'Verbena',
  'Vernonia',
  'Veronica',
  'Veronicastrum',
  'Vetiveria',
  'Viburnum',
  'Vicia',
  'Vigna',
  'Viguiera',
  'Vinca',
  'Vincetoxicum',
  'Viola',
  'Viscum',
  'Vitex',
  'Vitis',
  'Wasabia',
  'Washingtonia',
  'Weigela',
  'Weinmannia',
  'Wikstroemia',
  'Wisteria',
  'Withania',
  'Wittsteinia',
  'Wolffia',
  'Woodwardia',
  'Wyethia',
  'Xanthium',
  'Xanthoceras',
  'Xanthorhiza',
  'Xanthorrhoea',
  'Xerophyllum',
  'Xylosma',
  'Xyris',
  'Youngia',
  'Yucca',
  'Yushania',
  'Zannichellia',
  'Zantedeschia',
  'Zanthoxylum',
  'Zea',
  'Zelkova',
  'Zephyranthes',
  'Zieria',
  'Zizania',
  'Zizia',
  'Ziziphus',
  'Zostera',
  'Zoysia',
  'Zygophyllum'
];
const SALINITY_VALUES = ['tolerant', 'intolerant'];

module.exports = {
  convertToCrops,
  convertToCrop,

  getAsArray,

  PROPERTIES,
  ARRAY_PROPERTIES,

  BOOLEAN_VALUES,
  HARDINESS_ZONE_VALUES,
  SOIL_TEXTURE_VALUES,
  SOIL_PH_VALUES,
  SOIL_WATER_RETENTION_VALUES,
  SHADE_VALUES,
  SUN_VALUES,
  WATER_VALUES,
  DROUGHT_VALUES,
  ECOSYSTEM_NICHE_VALUES,
  LIFE_CYCLE_VALUES,
  HERBACEOUS_OR_WOODY_VALUES,
  DECIDUOUS_OR_EVERGREEN_VALUES,
  GROWTH_RATE_VALUES,
  MATURE_MEASUREMENT_UNIT_VALUES,
  MATURE_HEIGHT_VALUES,
  MATURE_WIDTH_VALUES,
  FLOWER_TYPE_VALUES,
  POLLINATORS_VALUES,
  FUNCTIONS_VALUES,
  GROW_FROM_VALUES,
  CUTTING_TYPE_VALUES,
  FERTILITY_VALUES,
  ROOT_ZONE_VALUES,
  FAMILY_VALUES,
  GENUS_VALUES,
  SALINITY_VALUES
};
